services:
  frontend:
    image: museme-frontend:v1
    hostname: museme-frontend
    env_file: 
      - ../frontend/.env.local
    ports:
      - 80:3000
    expose:
      - '80'
    networks:
      - public
      - backend
    depends_on:
      - backend
  backend:
    image: museme-frontend:v1
    hostname: museme-backend
    env_file:
      - ../backend/.env
    ports:
      - 3000:8000
    networks:
      - backend
      - db
    depends_on:
      - db
  db:
    image: museme-db:v1
    hostname: museme-db
    environment:
      MYSQL_ROOT_PASSWORD: ROMRAMRemRam!
      MYSQL_DATABASE: music_app
      MYSQL_USER: kody
      MYSQL_PASSWORD: ROMRAMRemRam!
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - db

volumes:
  db:

networks:
  public:
  backend:
  db: